//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuanLyPhatHanhSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agency_Paid_Debt
    {
        public int AgencyID { get; set; }
        public decimal Paid { get; set; }
        public decimal Debt { get; set; }
    
        public virtual Agency Agency { get; set; }
    }
}
