//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuanLyPhatHanhSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayForPub
    {
        public int Id { get; set; }
        public int PubID { get; set; }
        public Nullable<int> AdminID { get; set; }
        public string InvoiceID { get; set; }
        public string PaymentID { get; set; }
        public decimal PayTotal { get; set; }
        public System.DateTime DateCreate { get; set; }
    
        public virtual AdminA AdminA { get; set; }
        public virtual IssueInvoice IssueInvoice { get; set; }
        public virtual PaymentInvoice PaymentInvoice { get; set; }
        public virtual Publishing Publishing { get; set; }
    }
}
