//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuanLyPhatHanhSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentInvoice()
        {
            this.PayForPubs = new HashSet<PayForPub>();
            this.Pub_Debt = new HashSet<Pub_Debt>();
        }
    
        public string PaymentID { get; set; }
        public int PubID { get; set; }
        public System.DateTime PaymentCreate { get; set; }
        public decimal PaymentAmount { get; set; }
        public Nullable<int> AdminID { get; set; }
    
        public virtual AdminA AdminA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayForPub> PayForPubs { get; set; }
        public virtual Publishing Publishing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pub_Debt> Pub_Debt { get; set; }
    }
}
