//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuanLyPhatHanhSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pub_Debt
    {
        public int PDebtID { get; set; }
        public int PubID { get; set; }
        public string ReceiptID { get; set; }
        public string PaymentID { get; set; }
        public Nullable<decimal> PubInvoicePaid { get; set; }
        public Nullable<decimal> PubIssueDebt { get; set; }
        public decimal PubDebt { get; set; }
        public System.DateTime DateCreate { get; set; }
    
        public virtual PaymentInvoice PaymentInvoice { get; set; }
        public virtual Publishing Publishing { get; set; }
        public virtual Receipt Receipt { get; set; }
    }
}
