//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuanLyPhatHanhSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportSold
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReportSold()
        {
            this.ReportSoldDetails = new HashSet<ReportSoldDetail>();
        }
    
        public int ReportID { get; set; }
        public int AgencyID { get; set; }
        public Nullable<int> AdminConfirm { get; set; }
        public System.DateTime ReportDate { get; set; }
        public decimal SoldTotal { get; set; }
        public string InvoiceID { get; set; }
    
        public virtual AdminA AdminA { get; set; }
        public virtual Agency Agency { get; set; }
        public virtual IssueInvoice IssueInvoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportSoldDetail> ReportSoldDetails { get; set; }
    }
}
