//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteQuanLyPhatHanhSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revenue
    {
        public int Id { get; set; }
        public string InvoiceID { get; set; }
        public decimal InvoiceRevenue { get; set; }
        public decimal RevenueTotal { get; set; }
        public System.DateTime RevenueDate { get; set; }
    
        public virtual IssueInvoice IssueInvoice { get; set; }
    }
}
